"""Create initial tables

Revision ID: 4408c3d98edf
Revises: 
Create Date: 2025-09-21 03:12:20.721712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4408c3d98edf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_data', sa.JSON(), nullable=False),
    sa.Column('response_data', sa.JSON(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('log_hash', sa.String(), nullable=False),
    sa.Column('previous_log_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_id'), 'logs', ['id'], unique=False)
    op.create_index(op.f('ix_logs_log_hash'), 'logs', ['log_hash'], unique=True)
    op.create_index(op.f('ix_logs_previous_log_hash'), 'logs', ['previous_log_hash'], unique=True)
    op.create_index(op.f('ix_logs_verdict'), 'logs', ['verdict'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_logs_verdict'), table_name='logs')
    op.drop_index(op.f('ix_logs_previous_log_hash'), table_name='logs')
    op.drop_index(op.f('ix_logs_log_hash'), table_name='logs')
    op.drop_index(op.f('ix_logs_id'), table_name='logs')
    op.drop_table('logs')
    # ### end Alembic commands ###